//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class main
    {
        public string Username { get; set; }
        public string Music_name { get; set; }
        public string Musci_url { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
